-- MySQL Script generated by MySQL Workbench
-- Thu Jun 20 23:18:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema parcial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parcial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parcial` DEFAULT CHARACTER SET utf8 ;
USE `parcial` ;

-- -----------------------------------------------------
-- Table `parcial`.`recording`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcial`.`recording` (
  `recordist` INT NOT NULL,
  `background` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `loc_id` VARCHAR(45) NULL,
  `date_upload` VARCHAR(45) NULL,
  `internal_notes` VARCHAR(45) NULL,
  `original_image` VARCHAR(45) NULL,
  PRIMARY KEY (`recordist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcial`.`birdsong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcial`.`birdsong` (
  `NN` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `lumbral_ff` VARCHAR(45) NULL,
  `ID_xc` VARCHAR(45) NULL,
  `recording_recordist` INT NOT NULL,
  `audio_path` VARCHAR(45) NULL,
  INDEX `fk_birdsong_recording1_idx` (`recording_recordist` ASC) VISIBLE,
  PRIMARY KEY (`NN`),
  CONSTRAINT `fk_birdsong_recording1`
    FOREIGN KEY (`recording_recordist`)
    REFERENCES `parcial`.`recording` (`recordist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcial`.`syllable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcial`.`syllable` (
  `ID` INT NOT NULL,
  `No_Syllable` VARCHAR(45) NULL,
  `NN` VARCHAR(45) NULL,
  `umbral_FF` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `t_ini` VARCHAR(45) NULL,
  `t_end` VARCHAR(45) NULL,
  `birdsong_NN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `birdsong_NN`),
  INDEX `fk_syllable_birdsong1_idx` (`birdsong_NN` ASC) VISIBLE,
  CONSTRAINT `fk_syllable_birdsong1`
    FOREIGN KEY (`birdsong_NN`)
    REFERENCES `parcial`.`birdsong` (`NN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcial`.`coef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcial`.`coef` (
  `ID` INT NOT NULL,
  `syllable_id` VARCHAR(45) NULL,
  `a0` VARCHAR(45) NULL,
  `a1` VARCHAR(45) NULL,
  `a2` VARCHAR(45) NULL,
  `b0` VARCHAR(45) NULL,
  `b1` VARCHAR(45) NULL,
  `b2` VARCHAR(45) NULL,
  `syllable_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_coef_syllable1_idx` (`syllable_ID` ASC) VISIBLE,
  CONSTRAINT `fk_coef_syllable1`
    FOREIGN KEY (`syllable_ID`)
    REFERENCES `parcial`.`syllable` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcial`.`measures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcial`.`measures` (
  `ID` INT NOT NULL,
  `Trill_Rate` VARCHAR(45) NULL,
  `Trill_Manual` VARCHAR(45) NULL,
  `fmin_Trill` VARCHAR(45) NULL,
  `fmin_theme` VARCHAR(45) NULL,
  `no_theme` VARCHAR(45) NULL,
  `no_trill` VARCHAR(45) NULL,
  `syllable_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_measures_syllable1_idx` (`syllable_ID` ASC) VISIBLE,
  CONSTRAINT `fk_measures_syllable1`
    FOREIGN KEY (`syllable_ID`)
    REFERENCES `parcial`.`syllable` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcial`.`slices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcial`.`slices` (
  `to_tf` INT NOT NULL,
  `tf_Dt` VARCHAR(45) NULL,
  `f0` VARCHAR(45) NULL,
  `t_space` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `dt_df` VARCHAR(45) NULL,
  `measures_ID` INT NOT NULL,
  PRIMARY KEY (`to_tf`, `measures_ID`),
  INDEX `fk_slices_measures1_idx` (`measures_ID` ASC) VISIBLE,
  CONSTRAINT `fk_slices_measures1`
    FOREIGN KEY (`measures_ID`)
    REFERENCES `parcial`.`measures` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
